title: Joshua Lopez
title: [The title of your site]
tagline: [A very short description of your site's purpose, used as subtitle]
description: [A short description of your site's purpose (e.g. for search engines)]
#logo: /assets/images/
#descripttion: text below
show_downloads: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
